system:

  version: 1
  ready: false

  lang: en_US
  verbose: true

  communication:
    # système de communication entre les app
    redis:
      host: localhost
      port: 6379
      auth:
        enabled: false
        user: default
        has-password: true
        password: password
      database: 0
      timeout: 2000

    # système de stockage permanent
    postgre:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      database: propergol